name: CI
on:
  push:
    paths-ignore:
      - "doc/**"
      - "README.md"
      - "**.md"
      - "LICENSE**"
      - ".gitattributes"
      - ".gitignore"
      - ".vscode/**"
  pull_request:
    paths-ignore:
      - "doc/**"
      - "README.md"
      - "**.md"
      - "LICENSE**"
      - ".gitattributes"
      - ".gitignore"
      - ".vscode/**"
concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true
jobs:
  x86_64-linux:
    runs-on: ubuntu-latest
    # We want to run on external PRs, but not on our own internal PRs as they'll be run by the push
    # to the branch.
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository) && !contains(github.event.head_commit.message, '*skipbuild*')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          #lfs: true
          submodules: recursive

      #- name: Checkout LFS objects
      #  run: git lfs checkout

      - name: Read .zig-version
        id: zigversion
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.zigversion
          
      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ steps.zigversion.outputs.content }}
      
      - name: lint
        run: zig fmt --check ./src ./libs
      
      - name: x86_64-linux -> x86_64-linux-gnu
        run: zig build install -Dtarget=x86_64-linux-gnu --summary all

      - name: x86_64-linux -> x86_64-macos
        run: zig build install -Dtarget=x86_64-macos --summary all

      - name: x86_64-linux -> aarch64-macos
        run: zig build install -Dtarget=aarch64-macos --summary all

      - name: x86_64-linux -> x86_64-windows
        run: zig build install -Dtarget=x86_64-windows --summary all

      - name: test
        run: |
          zig build run-tests --summary all -freference-trace
